# Generated by Django 3.2.12 on 2022-03-29 16:17

from django.db import migrations, models
import django.db.models.deletion
import sns.apps.product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[sns.apps.product.models.Product.valuePositive])),
                ('brand', models.CharField(max_length=20)),
                ('imagelink', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[sns.apps.product.models.Product.valuePositive])),
                ('active', models.CharField(default='Y', max_length=1, validators=[sns.apps.product.models.Product.activeValidator])),
                ('storeid', models.ForeignKey(db_column='storeid', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
