# Generated by Django 3.2.12 on 2022-03-29 16:17

from django.db import migrations, models
import sns.apps.store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(default='Kitchener', max_length=30)),
                ('pincode', models.CharField(max_length=6, validators=[sns.apps.store.models.Store.lengthValidator])),
                ('active', models.CharField(default='Y', max_length=1, validators=[sns.apps.store.models.Store.activeValidator])),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
