# Generated by Django 3.2.12 on 2022-03-29 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sns.apps.order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('tipamount', models.DecimalField(decimal_places=2, max_digits=6, validators=[sns.apps.order.models.valuePositive])),
                ('orderamount', models.DecimalField(decimal_places=2, max_digits=6, validators=[sns.apps.order.models.valuePositive])),
                ('status', models.CharField(default='pending', max_length=50)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('checkedouttime', models.DateTimeField(null=True)),
                ('deliverytime', models.DateTimeField(null=True)),
                ('acceptedtime', models.DateTimeField(null=True)),
                ('canceledtime', models.DateTimeField(null=True)),
                ('acceptedby', models.ForeignKey(db_column='acceptedby', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acceptedby', to=settings.AUTH_USER_MODEL)),
                ('completionconfirmedby', models.ForeignKey(db_column='completionconfirmedby', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completionconfirmedby', to=settings.AUTH_USER_MODEL)),
                ('orderedby', models.ForeignKey(db_column='orderedby', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderedby', to=settings.AUTH_USER_MODEL)),
                ('storeid', models.ForeignKey(db_column='storeid', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[sns.apps.order.models.valuePositive])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[sns.apps.order.models.valuePositive])),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'orderproduct',
            },
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, to='user.group')),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'ordergroup',
            },
        ),
    ]
